import * as fs from "fs";
import * as path from "path";

const IMAGES_DIR = path.join(__dirname, "../Sign/images");
const OUTPUT_FILE = path.join(__dirname, "../src/data/signs.ts");

type HebrewShape = "משולש" | "עיגול" | "מלבן" | "מיוחד" | "לא ידוע";

function resolveShape(key: string): HebrewShape {
  if (key.startsWith("p")) return "לא ידוע";
  const n = parseInt(key.split("_")[0], 10);
  if (n >= 100 && n < 200) return "משולש";
  if (n >= 200 && n < 300) return "עיגול";
  if (n >= 300 && n < 400) return "מלבן";
  if (n >= 400 && n < 500) return "עיגול";
  if (n >= 500 && n < 600) return "מלבן";
  if (n >= 600 && n < 700) return "מלבן";
  if (n >= 700 && n < 800) return "מלבן";
  if (n >= 800 && n < 900) return "עיגול";
  if (n >= 900 && n < 1000) return "מיוחד";
  return "לא ידוע";
}

function resolveSeries(key: string): string {
  if (key.startsWith("p")) return "provisional";
  const n = parseInt(key.split("_")[0], 10);
  if (isNaN(n)) return "unknown";
  return `${Math.floor(n / 100)}xx`;
}

const VALID_PATTERN = /^sign_(p?\d+(_[bcd])?)\.png$/;

const files = fs.readdirSync(IMAGES_DIR);
const entries: string[] = [];

for (const filename of files) {
  const match = filename.match(VALID_PATTERN);
  if (!match) continue;
  const key = match[1]; // e.g. "103", "129_b", "p127"
  const shape = resolveShape(key);
  const series = resolveSeries(key);
  entries.push(
    `  "${key}": { number: "${key}", imageFile: "${filename}", shape: "${shape}", series: "${series}", available: true }`
  );
}

entries.sort((a, b) => {
  const ka = a.match(/"([^"]+)":/)?.[1] ?? "";
  const kb = b.match(/"([^"]+)":/)?.[1] ?? "";
  return ka.localeCompare(kb, undefined, { numeric: true });
});

const output = `// AUTO-GENERATED by scripts/generateSignsData.ts — do not edit manually
// Re-run: npm run generate:signs

export interface SignRecord {
  number: string;
  imageFile: string;
  shape: string;
  series: string;
  available: boolean;
}

export const SIGNS_DATA: Record<string, SignRecord> = {
${entries.join(",\n")}
};
`;

fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
console.log(`Generated ${entries.length} sign entries → ${OUTPUT_FILE}`);
